### ISSUE TITLE
1. Создание диаграммы физической модели базы данных

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#2]
Нужно создать диаграмму физической модели базы данных

**Comment by ppnmrnko** [comment]
![Диаграмма модели БД](https://github.com/nastushka283/coursework/assets/147037842/c276cca0-c386-4a63-92e9-718a2ebb7264)
Разработана диаграмма модели базы данных.

**Comment by ppnmrnko** [comment]
![Screenshot_118](https://github.com/nastushka283/coursework/assets/147037842/dccc656a-b65e-4cce-bfb2-f0bb05d43793)
Разработана диаграмма модели базы данных
