### ISSUE TITLE
3. Составить архитектурную диаграмму по проекту

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#21]
Необходимо, ориентируясь от проекта, составить для него архитектурную диаграмму

**Comment by ArtmnvRoman** [comment]
Была создана архитектурная диаграмма для данного проекта
![Архитектурная_диаграмма](https://github.com/nastushka283/coursework/assets/149421450/0e9d1c66-cfd6-4eb5-a962-9c63fb9c1eed)
