### ISSUE TITLE
4. Составить функциональную диаграмму UML по продукту

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#22]
Исходя из проекта, нужно составить функциональную диаграмму UML по продукту

**Comment by ArtmnvRoman** [comment]
Было создано несколько функциональных диаграмм, т.к под функциональной диаграммой можно понимать несколько видов диаграмм(диаграмма деятельности(активности) и нотация IDF0).
![Диаграмма активности(функциональная) для генерала](https://github.com/nastushka283/coursework/assets/149421450/c532f07d-6ffd-43be-b5ae-386b50ddf099)
![Диаграмма активности(функциональная) для солдата](https://github.com/nastushka283/coursework/assets/149421450/714d0da5-504a-428e-ac4f-90c682ab231d)
![Фунцкиональная диаграмма(нотация IDF0)](https://github.com/nastushka283/coursework/assets/149421450/6aea5738-65ec-4cfe-9313-9d172e15cd1f)

**Comment by ArtmnvRoman** [comment]
Была составлена функциональная диаграмма по нотации IDEF0
![функциональная_диаграмма_нотация_IDEF0](https://github.com/nastushka283/coursework/assets/149421450/de921793-f667-4bf9-ba70-4590dd6b833a)
