### ISSUE TITLE
5. Составить диаграмму последовательности UML для функции

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#23]
Необходимо выбрать одну функцию и составить для нее UML-диаграмму последовательности

**Comment by ArtmnvRoman** [comment]
Была создана диаграмма последовательности для функции изменения таблицы вооружения.
![Диаграмма последовательности](https://github.com/nastushka283/coursework/assets/149421450/c3dfea0b-88bf-490a-9964-6de2fda9d812)

**Comment by ArtmnvRoman** [comment]
Для выполнения этого задания была выбрана функция редактирования таблицы вооружения.
![Диаграмма_последовательности_UML](https://github.com/nastushka283/coursework/assets/149421450/6cae0539-f19a-40c6-ac64-f30e819fac1a)
