### ISSUE TITLE
6. Составить концептуальную модель базы данных

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#24]
Для нашей БД нужно составить концептуальную модель

**Comment by ArtmnvRoman** [comment]
Была составлена концептуальная модель БД
![Концептуальная модель БД 1](https://github.com/nastushka283/coursework/assets/149421450/f77e60ad-ed00-48bb-8ef4-5964c86749eb)
![Концептуальная модель БД 2](https://github.com/nastushka283/coursework/assets/149421450/09016f1d-e012-4977-85db-37e08c65c342)

**Comment by ArtmnvRoman** [comment]
Была построена концептуальная модель базы данных к нашему проекту.
![Концептуальная модель БД 1](https://github.com/nastushka283/coursework/assets/149421450/497be5ea-af4a-49fc-bccc-8f03bec23033)
![Концептуальная модель БД 2](https://github.com/nastushka283/coursework/assets/149421450/3b7e01c4-787a-42bb-86fe-4f6ad838ecff)
![Концептуальная модель БД 3](https://github.com/nastushka283/coursework/assets/149421450/4f0539e8-57df-4ad0-9330-6e9efd550c6c)
