### ISSUE TITLE
3. Добавление пользователей (admin, general, solder), выдача паролей и наделение их ролями

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#4]
Нужно воссоздать добавление пользователей (admin, general, solder), выдать им пароли и наделить их ролями

**Comment by ppnmrnko** [comment]
[роли.txt](https://github.com/nastushka283/coursework/files/13805209/default.txt)
Были созданы пользователи (admin, general, solder), для каждого пользователя были созданы роли

**Comment by ppnmrnko** [comment]
Отдельно для каждого пользователя были выданы пароли с помощью команд:
`ALTER USER general WITH PASSWORD 'пароль'`
`ALTER USER solder WITH PASSWORD 'пароль'`
`ALTER USER admin WITH PASSWORD 'пароль'`

*пароль - нейтральное слово, которое не обозначает действительный пароль пользователя. В данном примере не прописан действительный пароль для каждого пользователя из соображений безопасности.
