### ISSUE TITLE
5. Создание представлений и функций

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#6]
Для лучшей работы базы данных создать представления, хранимые функции и процедуры

**Comment by ppnmrnko** [comment]
[представления и функции.txt](https://github.com/nastushka283/coursework/files/13805273/default.txt)
[процедуры.txt](https://github.com/nastushka283/coursework/files/13805274/default.txt)
Были разработаны представления, хранимые функции и процедуры для правильной и удобной работы с базой данных
