### ISSUE TITLE
7. Создание web-интерфейса для работы с базой данных

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#8]
Необходимо создать web-интерфейс для работы с заданной базой данных

**Comment by ppnmrnko** [comment]
Был создан web-интерфейс представленный в виде сайта https://pg.venom56.ru/

**Comment by ppnmrnko** [comment]
Был создан web-интерфейс представленный в виде сайта https://pg.venom56.ru/

Разработанный сайт сочетает в себе простоту использования и эффективность, обеспечивая пользователям интуитивно понятный опыт работы с данными. Закрытие этой задачи является важным шагом в улучшении функциональности нашего проекта, и теперь пользователи могут легко управлять базой данных через стильный и удобный web-интерфейс.
