### ISSUE TITLE
8. Создание окна ввода пользователя и пароля

### ISSUE THREAD

**Issue by nastushka283** [nastushka283/coursework#9]
Необходимо составить окно ввода имени пользователя и пароля к нему

**Comment by ppnmrnko** [comment]
Было создано окно ввода имени пользователя и пароля к нему.
![Screenshot_134](https://github.com/nastushka283/coursework/assets/147037842/be9c99e0-4e9e-49a8-8dd5-01d8a0b4fcf9)
